version: '3.8'

services:
  writerside-builder:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/app
    command: /opt/builder/bin/idea.sh -Djava.awt.headless=true build --input-dir=/app --output-dir=/app/output
