version: '3.8'

services:
  writerside-builder:
    image: jetbrains/writerside-builder:2025.04.8412
    volumes:
      - .:/opt/sources
    environment:
      - SOURCE_DIR=/opt/sources
      - MODULE_INSTANCE=ds/hi # Assuming 'ds' is your instance ID and 'hi' is the module ID
      - OUTPUT_DIR=/opt/sources/output
      - RUNNER=other
    # The command is handled by the entrypoint of the image
    # command: /opt/builder/bin/idea.sh build --input-dir=/app --output-dir=/app/output
