name: Build Writerside Documentation

on: 
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Java
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Download and Unzip Writerside CLI
      run: |
        WRITERSIDE_VERSION=241.15989 # Use a known working version or find the latest
        wget https://download.jetbrains.com/writerside/writerside-cli-${WRITERSIDE_VERSION}.zip -O writerside-cli.zip
        unzip writerside-cli.zip -d writerside-cli
        echo "WRITERSIDE_CLI_HOME=$(pwd)/writerside-cli" >> $GITHUB_ENV
        echo "$(pwd)/writerside-cli/bin" >> $GITHUB_PATH

    - name: Build Writerside Documentation
      run: writerside.sh build --input-dir=. --output-dir=output

    - name: Upload documentation artifact
      uses: actions/upload-artifact@v4
      with:
        name: writerside-documentation
        path: output